# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170511_0855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
